services:
  - type: web
    name: slow-bot
    runtime: python
    plan: free
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: slowbot
      - key: OWNER_IDS
        sync: false
      - key: DEFAULT_PORT
        value: "80"
      - key: DEFAULT_CONN
        value: "250"
      - key: PING_INTERVAL
        value: "600"
