services:
  - type: web
    name: pinger-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: SELF_PING_INTERVAL_SECONDS
        value: "600"
      - key: MAX_REQUESTS_PER_JOB
        value: "10"
      - key: MAX_WINDOW_SECONDS
        value: "3600"
      - key: PYTHON_VERSION
        value: 3.11.9
